name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: nodejs 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: npm install
        run: npm install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: create .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //@ebuckleyk:registry=https://npm.pkg.github.com/
            //npm.pkg.github.com/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release PR or Publish to NPM
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}